package life.fallingu.commuity.commuity.mapper;

import java.util.List;
import life.fallingu.commuity.commuity.pojo.NotificationType;
import life.fallingu.commuity.commuity.pojo.NotificationTypeExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

@Mapper
public interface NotificationTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationtype
     *
     * @mbggenerated Sun Mar 13 11:07:22 CST 2022
     */
    int countByExample(NotificationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationtype
     *
     * @mbggenerated Sun Mar 13 11:07:22 CST 2022
     */
    int deleteByExample(NotificationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationtype
     *
     * @mbggenerated Sun Mar 13 11:07:22 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationtype
     *
     * @mbggenerated Sun Mar 13 11:07:22 CST 2022
     */
    int insert(NotificationType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationtype
     *
     * @mbggenerated Sun Mar 13 11:07:22 CST 2022
     */
    int insertSelective(NotificationType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationtype
     *
     * @mbggenerated Sun Mar 13 11:07:22 CST 2022
     */
    List<NotificationType> selectByExample(NotificationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationtype
     *
     * @mbggenerated Sun Mar 13 11:07:22 CST 2022
     */
    NotificationType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationtype
     *
     * @mbggenerated Sun Mar 13 11:07:22 CST 2022
     */
    int updateByExampleSelective(@Param("record") NotificationType record, @Param("example") NotificationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationtype
     *
     * @mbggenerated Sun Mar 13 11:07:22 CST 2022
     */
    int updateByExample(@Param("record") NotificationType record, @Param("example") NotificationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationtype
     *
     * @mbggenerated Sun Mar 13 11:07:22 CST 2022
     */
    int updateByPrimaryKeySelective(NotificationType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationtype
     *
     * @mbggenerated Sun Mar 13 11:07:22 CST 2022
     */
    int updateByPrimaryKey(NotificationType record);

    @Select("select * from notificationtype where type = #{type}")
    NotificationType selectByType(@Param("type") int type);
}