package life.fallingu.commuity.commuity.mapper;

import java.util.List;

import life.fallingu.commuity.commuity.dto.QuestionDTO;
import life.fallingu.commuity.commuity.pojo.Question;
import life.fallingu.commuity.commuity.pojo.QuestionExample;
import org.apache.ibatis.annotations.*;

import javax.annotation.security.PermitAll;

@Mapper
public interface QuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Sat Mar 12 11:32:21 CST 2022
     */
    int countByExample(QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Sat Mar 12 11:32:21 CST 2022
     */
    int deleteByExample(QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Sat Mar 12 11:32:21 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Sat Mar 12 11:32:21 CST 2022
     */
    int insert(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Sat Mar 12 11:32:21 CST 2022
     */
    int insertSelective(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Sat Mar 12 11:32:21 CST 2022
     */
    List<Question> selectByExampleWithBLOBs(QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Sat Mar 12 11:32:21 CST 2022
     */
    List<Question> selectByExample(QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Sat Mar 12 11:32:21 CST 2022
     */
    Question selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Sat Mar 12 11:32:21 CST 2022
     */
    int updateByExampleSelective(@Param("record") Question record, @Param("example") QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Sat Mar 12 11:32:21 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") Question record, @Param("example") QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Sat Mar 12 11:32:21 CST 2022
     */
    int updateByExample(@Param("record") Question record, @Param("example") QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Sat Mar 12 11:32:21 CST 2022
     */
    int updateByPrimaryKeySelective(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Sat Mar 12 11:32:21 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Sat Mar 12 11:32:21 CST 2022
     */
    int updateByPrimaryKey(Question record);

    @Select(value ="<script>"+"select * from question"+"<where> <if test='search!=null'>title regexp #{search}</if></where>"+"order by gmt_create desc"+"</script>")
    @Results(id = "questionDtoModelMap",value = {
            @Result(column = "id",property = "id"),
            @Result(column = "title",property = "title"),
            @Result(column = "description",property = "description"),
            @Result(column = "gmt_create",property = "gmtCreate"),
            @Result(column = "gmt_modified",property = "gmtModified"),
            @Result(column = "creator",property = "creator"),
            @Result(column = "comment_count",property = "commentCount"),
            @Result(column = "view_count",property = "viewCount"),
            @Result(column = "like_count",property = "likeCount"),
            @Result(column = "tag",property = "tag"),
            @Result(property = "user",
                    column = "creator",
                    one=@One(select = "life.fallingu.commuity.commuity.mapper.UserMapper.selectByPrimaryKey"))
    })
    List<QuestionDTO> listBySearch(@Param("search") String str);

    @Select(value = "select * from question where creator=#{id} order by gmt_create desc")
    @ResultMap(value = "questionDtoModelMap")
    List<QuestionDTO> listByUserId(@Param("id") Long id);

    @Select(value = "select * from question where id = #{id}")
    @ResultMap(value = "questionDtoModelMap")
    QuestionDTO findById(@Param("id") Long id);

    @Update(value = "update question set view_count = view_count +1 where id=#{id}")
    int incrById(@Param("id") Long id);

    @Update(value = "update question set comment_count = comment_count +1 where id=#{id}")
    int incrCommentById(@Param("id") Long id);

    @Select(value = "select id,title,tag from question where id!=#{id} and tag regexp #{tag}")
    List<QuestionDTO> getRelateList(Question ques);
}