package life.fallingu.commuity.commuity.pojo;

public class NotificationType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notificationtype.id
     *
     * @mbggenerated Sun Mar 13 11:07:22 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notificationtype.type
     *
     * @mbggenerated Sun Mar 13 11:07:22 CST 2022
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notificationtype.name
     *
     * @mbggenerated Sun Mar 13 11:07:22 CST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notificationtype.id
     *
     * @return the value of notificationtype.id
     *
     * @mbggenerated Sun Mar 13 11:07:22 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notificationtype.id
     *
     * @param id the value for notificationtype.id
     *
     * @mbggenerated Sun Mar 13 11:07:22 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notificationtype.type
     *
     * @return the value of notificationtype.type
     *
     * @mbggenerated Sun Mar 13 11:07:22 CST 2022
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notificationtype.type
     *
     * @param type the value for notificationtype.type
     *
     * @mbggenerated Sun Mar 13 11:07:22 CST 2022
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notificationtype.name
     *
     * @return the value of notificationtype.name
     *
     * @mbggenerated Sun Mar 13 11:07:22 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notificationtype.name
     *
     * @param name the value for notificationtype.name
     *
     * @mbggenerated Sun Mar 13 11:07:22 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}